modLoader="javafml"
loaderVersion="[40,)"
license="GPLv3"
issueTrackerURL="https://github.com/ozokuz/stonehaul/issues/"

[[mods]]
modId="stonehaul"
version="${file.jarVersion}"
displayName="Stonehaul"
displayURL="https://github.com/ozokuz/stonehaul"
logoFile="examplemod.png"
credits="IDK"
authors="Ozoku"
description='''
An earlygame overhaul mod.
'''

[[dependencies.stonehaul]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stonehaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stonehaul]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stonehaul]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.6.4,)"
    ordering="NONE"
    side="BOTH"